allowBuilds:
    '@reown/appkit': false
    protobufjs: true
peerDependencyRules:
    ignoreMissing:
        - '@solana/web3.js'
    allowedVersions:
        'typescript': '6.0.3'
overrides:
    '@paulmillr/qr': '0.3.0'
    'uuid': '14.0.1'
